name: Generic issue
description: Report an issue, a suggestion, SQL only fix.
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this form! Please make sure to fill all fields, including the Title above.
  - type: textarea
    id: description
    attributes:
      label: Description
      description: |
        Description of the problem or issue here.
        If this is a crash, post the crashlog (upload to https://gist.github.com/).
    validations:
      required: true