on:
  pull_request:
    types: [opened]

jobs:
  tag_issues:
    runs-on: ubuntu-latest
    name: Issue Labeler
    steps:
    - name: Issue Labeler
      id: issue-labeler
      uses: TrinityCore/GitHub-Actions@pr-labeler
      with:
        token: ${{ secrets.GITHUB_TOKEN }}