on:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  pr_labeler:
    if: github.repository == 'jackpoz/GithubTests'
    runs-on: ubuntu-latest
    name: Pull Request Labeler
    steps:
    - name: Pull Request Labeler
      id: pr-labeler
      uses: TrinityCore/GitHub-Actions@pr-labeler
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
